<?php
function whitepaper_blocks_register_fields() {
	if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5c744b5e93e4e',
		'title' => 'WhitePaper Blocks: Loop',
		'fields' => array(
			array(
				'key' => 'field_5c744b7df70a1',
				'label' => 'Title',
				'name' => 'title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5c744babf70a2',
				'label' => 'Block ID',
				'name' => 'block_id',
				'type' => 'text',
				'instructions' => 'A unique CSS ID for this block. Make sure to use all lower case and dashes instead of spaces',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5c744ca5f70a4',
				'label' => 'Post Type',
				'name' => 'post_type',
				'type' => 'select',
				'instructions' => 'What kind of posts do you want to show? You can choose blog posts, pages, or a custom post type.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'post' => 'post',
					'page' => 'page',
					'attachment' => 'attachment',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5c744c1ff70a3',
				'label' => 'Number of Posts to Display',
				'name' => 'num_posts',
				'type' => 'number',
				'instructions' => 'The maximum number of posts to be displayed from your selected post type',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 3,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => '',
				'step' => 1,
			),
			array(
				'key' => 'field_5c744f5af70a5',
				'label' => 'Post Classes',
				'name' => 'post_class',
				'type' => 'text',
				'instructions' => 'One or more CSS classes to be added to each post in this block. Separate classes with a space, but make sure that each class uses all lower case and dashes instead of spaces.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5c744ff7f70a6',
				'label' => 'Before Loop',
				'name' => 'before_loop_layout',
				'type' => 'textarea',
				'instructions' => 'Information to be placed before the loop. This will only be shown once, no matter how many posts are displayed. You can use HTML and Boostrap for formatting. You can also use handlebar codes to display dynamic information. This section is totally optional.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 16,
				'new_lines' => '',
			),
			array(
				'key' => 'field_5c74514ef70a7',
				'label' => 'Post Layout',
				'name' => 'post_layout',
				'type' => 'textarea',
				'instructions' => 'How would you like the individual posts in the loop to be laid out? You can use HTML and Boostrap for formatting. You can also use handlebar codes to display dynamic information. If you aren\'t sure, you can leave this blank and just use the default.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 16,
				'new_lines' => '',
			),
			array(
				'key' => 'field_5c745248f70a8',
				'label' => 'After Loop',
				'name' => 'after_loop_layout',
				'type' => 'textarea',
				'instructions' => 'Information to be placed after the loop. This will only be shown once, no matter how many posts are displayed. You can use HTML and Boostrap for formatting. You can also use handlebar codes to display dynamic information. This section is totally optional.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 16,
				'new_lines' => '',
			),
			array(
			'key' => 'field_5c96ba66d5584',
			'label' => 'Advanced Query Options',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
			),
			array(
				'key' => 'field_5c96d161ade01',
				'label' => 'Taxonomy Slug',
				'name' => 'taxonomy',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'category',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5c96d411ade02',
				'label' => 'Taxonomy Term',
				'name' => 'taxonomy_term',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'my-category',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5cb47d9ce7580',
				'label' => 'Offset',
				'name' => 'offset',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/loop',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5cad7f93184f4',
		'title' => 'WhitePaper Blocks: Carousel',
		'fields' => array(
			array(
				'key' => 'field_5cad7fa9125a0',
				'label' => 'Block ID',
				'name' => 'block_id',
				'type' => 'text',
				'instructions' => 'A unique CSS ID for this block. Make sure to use all lower case and dashes instead of spaces',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5cad7ffd125a1',
				'label' => 'Carousel Class',
				'name' => 'carousel_class',
				'type' => 'text',
				'instructions' => 'One or more CSS classes to be added to the carousel container. Separate classes with a space, but make sure that each class uses all lower case and dashes instead of spaces. This is a great place to use Bootstrap rows or containers.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'row no-gutters',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5cad8070125a2',
				'label' => 'Post Type',
				'name' => 'post_type',
				'type' => 'select',
				'instructions' => 'What kind of posts do you want to show? You can choose blog posts, pages, or a custom post type.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'post' => 'post',
					'page' => 'page',
					'attachment' => 'attachment',
					'ctas' => 'ctas',
					'portfolio' => 'portfolio',
					'testimonials' => 'testimonials',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5cad810b125a3',
				'label' => 'Number of Posts to Display',
				'name' => 'num_posts',
				'type' => 'number',
				'instructions' => 'The maximum number of posts to be displayed from your selected post type',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 3,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => 1,
			),
			array(
				'key' => 'field_5cad814e125a4',
				'label' => 'Post Classes',
				'name' => 'post_class',
				'type' => 'text',
				'instructions' => 'One or more CSS classes to be added to each post in this block. Separate classes with a space, but make sure that each class uses all lower case and dashes instead of spaces.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5cad819f125a5',
				'label' => 'Carousel Layout',
				'name' => 'carousel_layout',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 16,
				'new_lines' => '',
			),
			array(
				'key' => 'field_5cad81cd125a6',
				'label' => 'Carousel Indicators',
				'name' => 'carousel_indicators',
				'type' => 'true_false',
				'instructions' => 'Check here if you\'d like to display indicators for your carousel',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5cad8219125a7',
				'label' => 'Carousel Controls',
				'name' => 'carousel_controls',
				'type' => 'true_false',
				'instructions' => 'Check here if you\'d like to display control arrows for your carousel',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5cad823e125a8',
				'label' => 'Advanced Query Options',
				'name' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'open' => 0,
				'multi_expand' => 0,
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5cad8264125a9',
				'label' => 'Taxonomy Slug',
				'name' => 'taxonomy',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'category',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5cad8299125aa',
				'label' => 'Taxonomy Term',
				'name' => 'taxonomy_term',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'my-category',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/carousel',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));


	acf_add_local_field_group(array(
		'key' => 'group_5c7d7406e1258',
		'title' => 'WhitePaper Blocks: Hero',
		'fields' => array(
			array(
				'key' => 'field_5c7d741d2cfed',
				'label' => 'Background Image',
				'name' => 'background_image',
				'type' => 'image',
				'instructions' => 'The actual image that will be shown with content overlaying it',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'large',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5c7d7a21b8ad6',
				'label' => 'Block ID',
				'name' => 'block_id',
				'type' => 'text',
				'instructions' => 'A unique CSS ID for this block. Make sure to use all lower case and dashes instead of spaces',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5c7d798d2cfee',
				'label' => 'Hero Classes',
				'name' => 'hero_class',
				'type' => 'text',
				'instructions' => 'One or more CSS classes to be added to the hero image container. Separate classes with a space, but make sure that each class uses all lower case and dashes instead of spaces. This is a great place to use Bootstrap rows or containers.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'row',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5c7d7aa4b8ad7',
				'label' => 'Hero Overlay',
				'name' => 'hero_overlay',
				'type' => 'textarea',
				'instructions' => 'Any content you\'d like overlaid on the hero image. You can use HTML and Bootstrap here.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 16,
				'new_lines' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/hero',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	endif;
}

add_action('acf/init', 'whitepaper_blocks_register_fields');

/************ Load Choices for Post Type Field ******************/
function whitepaper_choice_generator( $field ) {
    //Change this to whatever data you are using.

    $field['choices'] = array();

    //Loop through whatever data you are using, and assign a key/value
		$types = get_post_types( array( 'public' => true ) );
    foreach($types as $type) {
        $field['choices'][$type] = $type;
    }
    return $field;
}
add_filter('acf/load_field/name=post_type', 'whitepaper_choice_generator');
?>
